export const dropdownDetalleData = [
    {
        "value": "fibra_600",
        "price": "$18.000/mes",
        "savingsText": "Ahorra hasta <strong>$XX.XXX en 12 meses</strong>",
        "IconChannels": [
            {
                "default": true,
                "AppsText": "No incluye apps de streaming",
            },
            {
                "active": false,
                "iconType": "marcas",
                "iconName": "disney-plus-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "marcas",
                "iconName": "max-icon-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "entel",
                "iconName": "entel-tv-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-46",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-90",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
        ],
        "iconsDetail": [
            {
                "iconType": "transversales",
                "iconName": "smart-tv-2",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Canales de TV",
            },
            {
                "iconType": "transversales",
                "iconName": "internet",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Incluido",
                "subtitleIcon": "Router",
            },
            {
                "iconType": "transversales",
                "iconName": "extensor",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Extensor",
            },
            {
                "iconType": "transversales",
                "iconName": "velocidad",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "600Mbps",
                "subtitleIcon": "Velocidad máxima",
            },
            {
                "iconType": "transversales",
                "iconName": "servicio-tecnico",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Costo $0",
                "subtitleIcon": "Instalación",
            },
        ],
    },

    {
        "value": "fibra_600+",
        "price": "$26.000/mes",
        "savingsText": "Ahorra hasta <strong>$XX.XXX en 12 meses</strong>",
        "IconChannels": [
            {
                "default": false,
                "AppsText": "No incluye apps de streaming",
            },
            {
                "active": true,
                "iconType": "marcas",
                "iconName": "disney-plus-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "marcas",
                "iconName": "max-icon-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "entel",
                "iconName": "entel-tv-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-46",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-90",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
        ],
        "iconsDetail": [
            {
                "iconType": "transversales",
                "iconName": "smart-tv-2",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Canales de TV",
            },
            {
                "iconType": "transversales",
                "iconName": "internet",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Incluido",
                "subtitleIcon": "Router",
            },
            {
                "iconType": "transversales",
                "iconName": "extensor",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Extensor",
            },
            {
                "iconType": "transversales",
                "iconName": "velocidad",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "600Mbps",
                "subtitleIcon": "Velocidad máxima",
            },
            {
                "iconType": "transversales",
                "iconName": "servicio-tecnico",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Costo $0",
                "subtitleIcon": "Instalación",
            },
        ],
    },

    {
        "value": "fibra_600_tv_lite",
        "price": "$29.000/mes",
        "savingsText": "Ahorra hasta <strong>$XX.XXX en 12 meses</strong>",
        "IconChannels": [
            {
                "default": false,
                "AppsText": "No incluye apps de streaming",
            },
            {
                "active": false,
                "iconType": "marcas",
                "iconName": "disney-plus-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "marcas",
                "iconName": "max-icon-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": true,
                "iconType": "entel",
                "iconName": "entel-tv-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": true,
                "iconType": "transversales",
                "iconName": "canales-46",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-90",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
        ],
        "iconsDetail": [
            {
                "iconType": "transversales",
                "iconName": "smart-tv-2",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "46 canales",
                "subtitleIcon": "Canales de TV",
            },
            {
                "iconType": "transversales",
                "iconName": "internet",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Incluido",
                "subtitleIcon": "Router",
            },
            {
                "iconType": "transversales",
                "iconName": "extensor",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Extensor",
            },
            {
                "iconType": "transversales",
                "iconName": "velocidad",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "600Mbps",
                "subtitleIcon": "Velocidad máxima",
            },
            {
                "iconType": "transversales",
                "iconName": "servicio-tecnico",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Costo $0",
                "subtitleIcon": "Instalación",
            },
        ],
    },
    
    {
        "value": "fibra_600_tv_full",
        "price": "$39.000/mes",
        "savingsText": "Ahorra hasta <strong>$XX.XXX en 12 meses</strong>",
        "IconChannels": [
            {
                "default": false,
                "AppsText": "No incluye apps de streaming",
            },
            {
                "active": true,
                "iconType": "marcas",
                "iconName": "disney-plus-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": true,
                "iconType": "marcas",
                "iconName": "max-icon-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": true,
                "iconType": "entel",
                "iconName": "entel-tv-2",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": false,
                "iconType": "transversales",
                "iconName": "canales-46",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
            {
                "active": true,
                "iconType": "transversales",
                "iconName": "canales-90",
                "iconClass": "image-xs-5",
                "iconFormat": "webp",
            },
        ],
        "iconsDetail": [
            {
                "iconType": "transversales",
                "iconName": "smart-tv-2",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "90 canales",
                "subtitleIcon": "Canales de TV",
            },
            {
                "iconType": "transversales",
                "iconName": "internet",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Incluido",
                "subtitleIcon": "Router",
            },
            {
                "iconType": "transversales",
                "iconName": "extensor",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "No incluido",
                "subtitleIcon": "Extensor",
            },
            {
                "iconType": "transversales",
                "iconName": "velocidad",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "600Mbps",
                "subtitleIcon": "Velocidad máxima",
            },
            {
                "iconType": "transversales",
                "iconName": "servicio-tecnico",
                "iconClass": "image-xs-2",
                "iconFormat": "webp",
                "titleIcon": "Costo $0",
                "subtitleIcon": "Instalación",
            },
        ],
    }
];